version: '3'
services:
  express1:
    build:
      context: ./express-1
    ports:
      - "3000:3000"
    networks:
      - app-network

  express2:
    build:
      context: ./express-2
    ports:
      - "3001:3000"
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "8085:3000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
